### ISSUE TITLE
maven-shade-plugin fails on updated sample-broker

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1029]
After the java 11 update, the maven-shade plugin fails to build the broker jar file. [Here's the error](https://travis-ci.com/powertac/sample-broker/builds/130047070?utm_medium=notification&utm_source=email).

**Comment by jecollins** [comment]
The error was encountered in the Travis build. When building locally, we get warnings about duplicate classes in included jar files:

[WARNING] xpp3_min-1.1.4c.jar, xmlpull-1.1.3.1.jar define 2 overlapping classes: 
[WARNING]   - org.xmlpull.v1.XmlPullParserException
[WARNING]   - org.xmlpull.v1.XmlPullParser
[WARNING] javax.jms-api-2.0.1.jar, geronimo-jms_1.1_spec-1.1.1.jar define 58 overlapping classes: 
[WARNING]   - javax.jms.QueueConnection
[WARNING]   - javax.jms.MessageNotReadableException
[WARNING]   - javax.jms.ObjectMessage
[WARNING]   - javax.jms.TopicRequestor
[WARNING]   - javax.jms.JMSException
[WARNING]   - javax.jms.InvalidSelectorException
[WARNING]   - javax.jms.Message
[WARNING]   - javax.jms.Topic
[WARNING]   - javax.jms.ServerSessionPool
[WARNING]   - javax.jms.JMSSecurityException
[WARNING]   - 48 more...
[WARNING] commons-logging-1.2.jar, spring-jcl-5.1.9.RELEASE.jar define 5 overlapping classes: 
[WARNING]   - org.apache.commons.logging.Log
[WARNING]   - org.apache.commons.logging.impl.SimpleLog
[WARNING]   - org.apache.commons.logging.LogFactory$1
[WARNING]   - org.apache.commons.logging.impl.NoOpLog
[WARNING]   - org.apache.commons.logging.LogFactory
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/

Attempting to run this jar fails:

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.powertac.samplebroker.core.BrokerMain.main(BrokerMain.java:38)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
	at org.powertac.samplebroker.core.BrokerRunner.<clinit>(BrokerRunner.java:45)
	... 1 more

So it appears that the version of log4j we are using is not compatible with Java 11? Or perhaps when selecting among duplicate candidates (see above) an older version was selected?

**Comment by jecollins** [comment]
This was resolved in [a commit](https://github.com/powertac/powertac-core/commit/4984fc3e926bfebc8df02e334bfb760e213b815e
) to powertac-core.
