### ISSUE TITLE
Old brokers built with Java 8 won't run in new server 1.7.x

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1043]
This is a follow-on to Issue #1042. We get a fatal JMS error when starting up an old broker under Java 11.

**Comment by jecollins** [comment]
I think perhaps the problem is not as simple as the title suggests. Today I started up the 1.6.0 server using a Java 11 runtime, and the 1.6.0 broker still fails in exactly the same way:
```
Exception in thread "main" java.lang.IllegalArgumentException: Property 'connectionFactory' is required
	at org.springframework.jms.support.JmsAccessor.afterPropertiesSet(JmsAccessor.java:169)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.afterPropertiesSet(AbstractJmsListeningContainer.java:165)
	at org.powertac.samplebroker.core.JmsManagementService.registerMessageListener(JmsManagementService.java:112)
	at org.powertac.samplebroker.core.PowerTacBroker.run(PowerTacBroker.java:260)
	at org.powertac.samplebroker.core.PowerTacBroker.startSession(PowerTacBroker.java:185)
	at org.powertac.samplebroker.core.BrokerRunner.processCmdLine(BrokerRunner.java:173)
	at org.powertac.samplebroker.core.BrokerMain.main(BrokerMain.java:39)
```

**Comment by jecollins** [comment]
Turns out that old brokers work fine and interact correctly with the new server if you run them under Java 8 rather than Java 11. Beyond this, it's hard to see how to fix this problem without re-compiling the old brokers with a newer version of broker-core.
