### ISSUE TITLE
SNAPSHOT server fails to run game using boot record from 2019 finals

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1046]
This was first reported by Lampros on 23 March 2020. Some symptoms of the error:

At the console:
```Exception in thread "Thread-7" java.lang.Error: Could not find weather forecast for timeslot 361
	at org.powertac.factoredcustomer.DefaultCapacityOriginator.computeForecastCapacity(DefaultCapacityOriginator.java:177)
	at org.powertac.factoredcustomer.DefaultCapacityOriginator.getForecastCapacity(DefaultCapacityOriginator.java:153)
```

In the server trace log:
```12368 INFO  factoredcustomer.DefaultFactoredCustomer: Customer BrooksideHomes evaluating tariffs at timeslot 360
12369 INFO  server.CompetitionControlService: Final balance (brokername:balance) [ "default broker":0.0 "Sample":0.0 ]
12636 INFO  server.WeatherService: 24 WeatherReports fetched from xml response.
12637 INFO  server.WeatherService: 576 WeatherForecasts fetched from xml response.
12703 WARN  TransportConnection.Transport: Transport Connection to: tcp://127.0.0.1:57828 failed: java.io.EOFException
15120 INFO  server.CompetitionControlService: pause
22659 WARN  listener.DefaultMessageListenerContainer: Setup of JMS message listener invoker failed for destination 'serverInput' - trying to recover. Cause: java.lang.InterruptedException
22662 ERROR listener.DefaultMessageListenerContainer: Could not refresh JMS Connection for destination 'serverInput' - retrying using FixedBackOff{interval=5000, currentAttempts=0, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
22670 ERROR listener.DefaultMessageListenerContainer: Could not refresh JMS Connection for destination 'serverInput' - retrying using FixedBackOff{interval=5000, currentAttempts=1, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
22671 ERROR listener.DefaultMessageListenerContainer: Stopping container for destination 'serverInput': back-off policy does not allow for further attempts.
```

In the state log:
```12276:org.powertac.common.BalancingTransaction::5275::new::1876::360::-26508.835990853022::-5606.853043897753
12276:org.powertac.common.msg.BalanceReport::5276::new::360::-26508.835990853022
12277:org.powertac.common.Tariff::1878::setState::OFFERED
12277:org.powertac.common.Tariff::1881::setState::OFFERED
12277:org.powertac.common.Tariff::1884::setState::OFFERED
12369:org.powertac.common.msg.SimEnd::null::new
12406:org.powertac.common.WeatherReport::5277::new::432::6.0::11.0::290.0::0.25
12406:org.powertac.common.WeatherReport::5278::new::433::6.2::12.0::290.0::1.0
12406:org.powertac.common.WeatherReport::5279::new::434::6.1::9.0::300.0::0.875
```

So it's timeslot 360, and the server issues the SimEnd message before the weather reports and forecasts arrive. The only place this message is generated is in `CompetitionControlService.shutDown()`. This is called only from `SimRunner.run()` when either the correct number of timeslots have passed, or four exceptions have been thrown somewhere in the `step()` operation. The JMS errors may be outside this scope, bypassing the "max-exceptions" count.

The error occurs while BrooksideHomes is evaluating tariffs for the first time. A number of other customers have evaluated tariffs before this point, but BrooksideHomes is the first of the factored-customer models to evaluate. If we look at the trace log above, a batch of weather reports and forecasts arrive while this is happening at 12636. Then at 12703 we get the network error, and everything seems to stop until the watchdog timer intercedes at 15120. Then another 6.5 seconds pass until the final JMS error shuts everything down.

**Comment by jecollins** [comment]
This appears to be a regression, because the problem does not occur with a freshly-generated boot record. Perhaps it is connected to differences between a 1.6.0 boot record and the 1.7.0-SNAPSHOT server which writes a boot record with a bit more information.

**Comment by jecollins** [comment]
I suspect this is not a backward-compatibility issue, but a local-vs-tournament compatibility issue. The weather data set used in the tournament is not recorded in the boot record, it's in the configuration. The default location is Rotterdam, and the default start time is 10 October 2009. We never use Rotterdam data for tournaments. The base time in the boot record is more than 4.5 years later than this. It's quite possible that weather data for Rotterdam at that time does not exist. Indeed, if you try to retrieve Rotterdam data from the weather server for September 2014 it hangs.

**Comment by jecollins** [comment]
It turns out this problem is well-known, which is why if you want to use an old boot record file, especially one from a tournament, you need to use the state log from the same game as a source of weather data. The weather service inside the server catches exceptions properly, but the behavior of the weather server in this case is to time out. That's why the server pause is invoked. Unfortunately, there's a shorter timeout in the server which is causing the exit.
