### ISSUE TITLE
Server crash, master branch 1.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1080]
Exception in thread "Thread-80" java.util.NoSuchElementException
	at java.base/java.util.TreeMap.key(TreeMap.java:1324)
	at java.base/java.util.TreeMap.firstKey(TreeMap.java:289)
	at org.powertac.common.repo.OrderbookRepo.doCleanup(OrderbookRepo.java:181)
	at org.powertac.common.repo.ManagedRepo$1.perform(ManagedRepo.java:57)
	at org.powertac.common.RepeatingTimedAction.perform(RepeatingTimedAction.java:43)
	at org.powertac.common.TimeService.runActions(TimeService.java:352)
	at org.powertac.common.TimeService.updateTime(TimeService.java:160)
	at org.powertac.server.SimulationClockControl.waitForTick(SimulationClockControl.java:248)

**Comment by jecollins** [comment]
Not reproducible. old news.
