### ISSUE TITLE
Invalid tariff specification raises exception in server

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1095]
In game 14 of the first 2021 trial competition, CrocodileAgent2020 issued two tariffs with Rates containing NaN values for minValue. Validation is supposed to catch this in `handleMessage (TariffSpecification spec)` by calling `spec.isValid()` which in turn calls `rate.isValid()` on all the Rates. This exact case is tested in `RateTests.testRateValidity()`. But apparently at runtime an exception is thrown in the logger, presumably when trying to log the cause of the failed validity test: 

```
1298789 ERROR tariffmarket.TariffMarketService: Cannot call handleMessage: java.lang.NullPointerException
  ..at org.apache.logging.log4j.core.filter.ThresholdFilter.filter(ThresholdFilter.java:74)
  ..at org.apache.logging.log4j.core.filter.ThresholdFilter.filter(ThresholdFilter.java:59)
  ..at org.apache.logging.log4j.core.Logger$PrivateConfig.filter(Logger.java:447)
  ..at org.apache.logging.log4j.core.Logger.isEnabled(Logger.java:170)
```

As a result, the broker does not receive the invalidSpec message. This sequence can be seen twice in the game 14 logs, the first at the 1298789 msec point.

**Comment by jecollins** [comment]
The code in this case now just says the value is NaN rather than trying to log the actual value.
