### ISSUE TITLE
org.powertac.util.MessageDispatcher::dispatch fails on empty args

### ISSUE THREAD

**Issue by fmilkau** [powertac/powertac-server#1124]
The MessageDispatcher throws an ArrayIndexOutOfBoundsException if the last parameter (args/messages) is empty.

Occurred when trying to apply a new log tool with core version **1.8.1** on a **2019 finals log**.

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.powertac.util.MessageDispatcher.dispatch(MessageDispatcher.java:66)
	at org.powertac.logtool.common.DomainObjectReader.dispatchMessageListeners(DomainObjectReader.java:370)
	at org.powertac.logtool.common.DomainObjectReader.fireNewObjectEvent(DomainObjectReader.java:340)
	at org.powertac.logtool.common.DomainObjectReader.readObject(DomainObjectReader.java:261)
	at org.powertac.logtool.LogtoolCore.readStateLog(LogtoolCore.java:259)
	at org.powertac.logtool.LogtoolCore.readStateLog(LogtoolCore.java:161)
	at org.powertac.logtool.LogtoolCore.readStateLog(LogtoolCore.java:152)
	at org.powertac.logtool.LogtoolContext.cli(LogtoolContext.java:140)
	at org.powertac.analyzer.util.AbstractExtractor.run(AbstractExtractor.java:22)
	at org.powertac.analyzer.tariff.TariffTransactions.main(TariffTransactions.java:19)
```

**Comment by jecollins** [comment]
Any changes we make to correct this will show up in the 1.9 or later version, unless there is a strong argument for making a new 1.8 release.

**Comment by jecollins** [comment]
Added a test for dispatch() with several arg combinations including no args. Test passes, update deployed to 1.9.0-SNAPSHOT.
