### ISSUE TITLE
Sample broker fails to open JMS connection

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#900]
On my two Ubuntu 16.04 LTS installations, the sample broker no longer logs into the server correctly. The error message is:

5311 WARN  activemq.ActiveMQSessionExecutor: Received a message on a connection which is not yet started. Have you forgotten to call Connection.start()? Connection: ActiveMQConnection {id=ID:hazel-40016-1475505728224-1:1,clientId=ID:hazel-40016-1475505728224-0:1,started=false}

Looking through broker-core/.../JmsManagementService, we can see that the variable connectionOpen is never set to true. This is not new; it has been this way at least back to 2012. It's unclear, however, whether this is the source of the problem. Most likely there is some sort of misconfiguration or missing code that's only exposed with the updated Spring and AMQ libraries, and the newer networking setup in Ubuntu 16.04.

**Comment by erikkemperman** [comment]
For what it's worth, I am not seeing this problem -- on the updated Spring and AMQ as well, and on Linux Mint "Sarah", which is derivative of Ubuntu 16.04. Not 100% sure to what extent networking is different between Mint and Ubuntu but would guess hardly different at all.

I've tracked the history of the the `openConnection` field, because I was curious -- I can't see how it's ever anything but `false`, currently.  I don't think has anything to do with AMQ, directly, but rather it looks like it served (briefly) as a marker around queue cleanup of our own devising? If so I think it could/should be removed to avoid confusion?

The `openConnection` field was introduced before broker-core was factored out of sample-broker, on 5th of July 2012, here:
https://github.com/powertac/sample-broker/commit/9819762e616eea1d184e0ed04c840b94928d53b5#diff-35d4b4b2e9d18f50886d51121bb3d1e6R65
At this point it sets `openConnection = true` when creating the queue (line 126 of same patch).
But this was then commented later the same day:
https://github.com/powertac/sample-broker/commit/1dac56fcba26172dcd4345fa8e4322943abd4bc8#diff-35d4b4b2e9d18f50886d51121bb3d1e6R124
And removed the next day:
https://github.com/powertac/sample-broker/commit/6d5a575351a9f145f23cb9ddb1e89897a1c35900#diff-35d4b4b2e9d18f50886d51121bb3d1e6L124

**Comment by jecollins** [comment]
This appears to be a server problem rather than a broker problem, and it's happening on the currently deployed 1.4.0-SNAPSHOT version. Here's the error in the server log:

```
59285 INFO  server.CompetitionSetupService: Found 539 bootstrap nodes
59856 ERROR server.JmsManagementService: Failed to create queue serverInput
javax.jms.JMSException: org.apache.activemq.advisory.AdvisorySupport.isVirtualDestinationConsumerAdvisoryTopic(Lorg/apache/activemq/command/ActiveMQDestination;)Z
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1401) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.AdvisoryConsumer.<init>(AdvisoryConsumer.java:51) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.ActiveMQConnection.ensureConnectionInfoSent(ActiveMQConnection.java:1513) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.ActiveMQConnection.createSession(ActiveMQConnection.java:324) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.springframework.jms.connection.SingleConnectionFactory.createSession(SingleConnectionFactory.java:437) ~[spring-jms-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.jms.connection.CachingConnectionFactory.getSession(CachingConnectionFactory.java:236) ~[spring-jms-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory$SharedConnectionInvocationHandler.invoke(SingleConnectionFactory.java:604) ~[spring-jms-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at com.sun.proxy.$Proxy196.createSession(Unknown Source) ~[?:?]
        at org.powertac.server.JmsManagementService.createQueue(JmsManagementService.java:174) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
        at org.powertac.server.JmsManagementService.initializeServerQueue(JmsManagementService.java:69) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
        at org.powertac.server.CompetitionControlService.init(CompetitionControlService.java:179) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
```

**Comment by jecollins** [comment]
This is not exactly a bug, and it's not in the broker. The server problem was resolved by blowing away files/* in server-distribution and re-starting the viz. I'm going to close this one and wait until we see more clearly why this happens -- or if it ever happens again.
