### ISSUE TITLE
NPE in CustomerModelService if model missing from config file

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#932]
The current code fails if not every available model type is configured at startup. It should be possible to omit model types for a particular config. Here's the NPE when one type is missing from config:
```
Exception in thread "Thread-6" java.lang.NullPointerException
	at org.powertac.customer.CustomerModelService.initialize(CustomerModelService.java:116)
	at org.powertac.server.CompetitionControlService.configurePlugins(CompetitionControlService.java:660)
       ...
```

**Comment by jecollins** [comment]
Ensure that null cannot be returned in this case, added test.
