### ISSUE TITLE
Sample Broker test fails

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#990]
Running 'mvn test' fails, with errors pointing at the maven-surefire-plugin.
The configuration of this plugin seems to be broken for some time.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project sample-broker: There are test failures.
[ERROR] 
[ERROR] Please refer to /tmp/powertac/sample-broker/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /tmp/powertac/sample-broker && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /tmp/powertac/sample-broker/target/surefire/surefirebooter5822190405348981375.jar /tmp/powertac/sample-broker/target/surefire 2018-11-16T13-27-28_966-jvmRun1 surefire2148585808728553422tmp surefire_07620893272636639468tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /tmp/powertac/sample-broker && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /tmp/powertac/sample-broker/target/surefire/surefirebooter5822190405348981375.jar /tmp/powertac/sample-broker/target/surefire 2018-11-16T13-27-28_966-jvmRun1 surefire2148585808728553422tmp surefire_07620893272636639468tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by jecollins** [comment]
I just re-cloned and re-built the whole system in a clean environment. I don't see any issues. What environment are you using when this happens? What mvn goal were you using?

**Comment by govertbuijs** [comment]
'mvn test' fails for me after clearing my .m2 repository on a fresh git clone
I tried it with the version from june 1st (6d71a249) and it fails as well.

**Comment by jecollins** [comment]
OK, I tried that. deleted ~/.m2/repository/*, downloaded a fresh clone of sample-broker, ran mvn test. Everything works. The target/surefire-reports dir seems to be correctly populated. Is there something else different in your env? I'm running Ubuntu 18.04 LTS.

**Comment by govertbuijs** [comment]
Ubuntu 18.04.1 LTS / openjdk version "1.8.0_181" / Apache Maven 3.5.2

This also seem to happen on a Windows env.

**Comment by govertbuijs** [comment]
It also happened on powertac-core. Sample broker might inherit the problem from there.

**Comment by govertbuijs** [comment]
This seem to offer a solution : https://stackoverflow.com/a/50661649
If i add the clas-loader line to the powertac-core pom, both modules seem to 'mvn test' fine.

**Comment by jecollins** [comment]
Are you willing to commit it or issue a PR? Otherwise I could try it, but I'm not seeing the problem.

**Comment by jecollins** [comment]
Can you confirm that this is fixed?

**Comment by govertbuijs** [comment]
This is fixes on my environments.
It seems this was only  a problem on OpenJDK, not on the Oracle JDK.
